translate guide/external-dom-mutations to french
xtuc/preact-www pull request #12
Opened 2017-11-29 10:45 UTC by drazik

2017-11-29 18:00 UTC, mlcdf requested changes
Merci !

2017-11-29 18:00 UTC, mlcdf commented on content/lang/fr/guide/external-dom-mutations.md
> +Vous pouvez aussi voir cette technique en actio dans [preact-token-input](https://github.com/developit/preact-token-input/blob/master/src/index.js) - cela utilise un composant comme point d'appui dan
action*

2017-11-30 10:10 UTC, xtuc approved these changes

2017-11-30 18:23 UTC, mlcdf approved these changes

2017-11-30 18:23 UTC, merged