translate guide/switching-to-preact to french
xtuc/preact-www pull request #15
Opened 2017-11-29 16:19 UTC by drazik

2017-11-29 16:58 UTC, xtuc approved these changes
Super! merci pour ton taff

2017-11-29 17:51 UTC, mlcdf requested changes
Quelques oublis/coquilles.

Merci !

2017-11-29 17:51 UTC, mlcdf commented on content/lang/fr/guide/switching-to-preact.md
> +Une fois ces dépendences installées, configurez votre système de build pour remplacer les imports de React afin qu'ils pointent vers Preact.
dépendances*

2017-11-29 17:51 UTC, mlcdf commented on content/lang/fr/guide/switching-to-preact.md
> +Alternativement, vous pouvez automatiquement convertise vos appels à `createClass()` vers des classes ES en utilisant [preact-codemod](https://github.com/vutran/preact-codemod) de Vu Tran.
couvertir*

Classes ES ? ES6 ?

2017-11-29 17:51 UTC, mlcdf commented on content/lang/fr/guide/switching-to-preact.md
> +Les références par chaîne de caractères sont dépréciées dans React et vont être supprimée sous peu, car elles introduisent trop de compléxité pour peu de gains.
supprimées*

2017-11-29 17:51 UTC, mlcdf commented on content/lang/fr/guide/switching-to-preact.md
> +Les références par chaîne de caractères sont dépréciées dans React et vont être supprimée sous peu, car elles introduisent trop de compléxité pour peu de gains.
complexité*

2017-11-29 17:52 UTC, mlcdf commented on content/lang/fr/guide/switching-to-preact.md
> +Alternativement, vous pouvez automatiquement convertise vos appels à `createClass()` vers des classes ES en utilisant [preact-codemod](https://github.com/vutran/preact-codemod) de Vu Tran.
Classes ES6 ?

2017-11-30 18:22 UTC, mlcdf approved these changes

2017-11-30 18:22 UTC, merged