translate guide/unit-testing-with-enzyme to french
xtuc/preact-www pull request #20
Opened 2017-11-30 13:40 UTC by drazik

2017-11-30 15:01 UTC, xtuc approved these changes

2017-11-30 18:31 UTC, mlcdf requested changes

2017-11-30 18:31 UTC, mlcdf commented on content/lang/fr/guide/unit-testing-with-enzyme.md
> +Utilisant Karma comme test runner, nous alons devoir ajouter quelques [`alias webpack`](https://github.com/webpack-contrib/karma-webpack#usage) pour React et quelques autres modules :
allons*

2017-12-01 09:32 UTC, drazik commented on content/lang/fr/guide/unit-testing-with-enzyme.md
> +Utilisant Karma comme test runner, nous alons devoir ajouter quelques [`alias webpack`](https://github.com/webpack-contrib/karma-webpack#usage) pour React et quelques autres modules :
voici 👍

2017-12-01 09:32 UTC, merged