[WIP] translate about/project-goals in french
xtuc/preact-www pull request #7
Opened 2017-08-02 14:55 UTC by drazik

2017-08-02 20:42 UTC, mlcdf requested changes

2017-08-02 20:42 UTC, mlcdf commented on content/lang/fr/about/project-goals.md
> +Certaines fonctionnalités de React sont volontairement absente de Preact, soit parce qu'elles ne sont pas réalisables en prenant en compte les objectifs principaux de Preact listés ci-dessus ou parce
absentes*

2017-08-02 20:42 UTC, mlcdf commented on content/lang/fr/about/project-goals.md
> +    - les PropTypes, qui peuvent facilement être utilisée comme une bibliothèque tierce
utilisées*

2017-08-02 20:42 UTC, mlcdf commented on content/lang/fr/about/project-goals.md
> +- **Compatibilité:** Preact a pour but d'être _largement compatible_ avec l'API de React. [preact-compat]  tente d'ajouter le maximum de compatibilité possible avec React.
Il y a un double espace après `[preact-compat]`

2017-08-03 06:45 UTC, xtuc approved these changes
Merci @mlcdf pour la review et @drazik pour la PR!

2017-08-03 06:45 UTC, xtuc commented on content/lang/fr/about/project-goals.md
> +- **Efficacité:** Utilisation efficace de la mémoire _(recyclage, éviter le ramasse-miettes)_
C'est plus tout à fait vrai dans Preact 8. Le recyclage a été supprimé car trop coûteux à maintenir et le fait de garder des références vers plein de noeuds du DOM (séparé par type car immuable) prenait lui meme beaucoup de mémoire.

J'imagine que c'était dans la doc en EN alors lgtm

2017-08-03 19:59 UTC, drazik commented on content/lang/fr/about/project-goals.md
> +- **Efficacité:** Utilisation efficace de la mémoire _(recyclage, éviter le ramasse-miettes)_
Oui, c'était dans la doc en anglais

2017-08-04 08:49 UTC, mlcdf approved these changes
C'est bon pour moi ! :+1:

2017-08-04 08:54 UTC, drazik commented
Au niveau du merge, vous préférez un commit de merge, un squash ou un rebase ? @mlcdf @xtuc

2017-08-04 14:12 UTC, mlcdf commented
Ça m'est entièrement égal.

2017-08-04 14:15 UTC, merged